name: assets_file_generator
description: A Flutter package that automatically generates Dart classes for assets by watching the assets folder.
version: 0.0.1
homepage: https://github.com/Mohamed-Hussien10/assets_file_generator
repository: https://github.com/Mohamed-Hussien10/assets_file_generator.git

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  macos:
  linux:
  windows:

flutter:
  # No assets or fonts needed here since this is a generator tool